name: ssidl-prototype

include:
  - path: ./ssidl-proxy/docker-compose.yaml
  - path: ./ssidl-package-registry/docker-compose.yaml

services:
  terminology-service:
    image: sbojanowski/ssidl-terminology-service:latest
    container_name: ssidl-terminology-service
    restart: always
    ports:
      - "8091:8091"
    environment:
      - SERVER_PORT=8091
      - HAPI_FHIR_PACKAGES_PRIMARYREGISTRYURL=http://nginx/registry/
    depends_on:
      - nginx     
      - verdaccio
    networks:
      - ssidl-network
  catalog-service:
    image: sbojanowski/ssidl-catalog-service:latest
    container_name: ssidl-catalog-service
    restart: always
    ports:
      - "8092:8092"
    environment:
      - SERVER_PORT=8092
      - HAPI_FHIR_PACKAGES_PRIMARYREGISTRYURL=http://nginx/registry/
      - HAPI_FHIR_VALIDATION_REQUESTSENABLE=false
      - HAPI_FHIR_VALIDATION_RESPONSESENABLE=false
      - SPRING_DATASOURCE_PERSISTANCE_STORE_URL=jdbc:postgresql://host.docker.internal:5432/catalog_service
    depends_on:
      - nginx     
      - verdaccio
    networks:
      - ssidl-network
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  ssidl-network:
    external: true