name: ssidl-prototype

include:
  - path: ../ssidl-proxy/docker-compose.yaml
  - path: ../ssidl-package-registry/docker-compose.yaml

services:
  terminology-service:
    image: sbojanowski/ssidl-terminology-service:latest
    container_name: ssidl-terminology-service
    restart: always
    ports:
      - "8091:8091"
    environment:
      - SERVER_PORT=8091
      - HAPI_FHIR_PACKAGES_PRIMARYREGISTRYURL=http://ssidl-nginx:8080/registry
    depends_on:
      - nginx     
      - verdaccio
    networks:
      - ssidl-network
  catalog-service:
    image: sbojanowski/ssidl-catalog-service:latest
    container_name: ssidl-catalog-service
    restart: always
    ports:
      - "8092:8092"
    environment:
      - SERVER_PORT=8092
      - HAPI_FHIR_PACKAGES_PRIMARYREGISTRYURL=http://ssidl-nginx:8080/registry
      - HAPI_FHIR_VALIDATION_REQUESTSENABLE=false
      - HAPI_FHIR_VALIDATION_RESPONSESENABLE=false
    depends_on:
      - nginx     
      - verdaccio
    networks:
      - ssidl-network

networks:
  ssidl-network:
    external: true