name: ssidl-proxy-test

services:
  nginx:
    image: nginx:stable
    container_name: ssidl-nginx-test
    ports:
      - "80:80"
    volumes:
      - ./config/nginx-test.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - ssidl-network
    restart: unless-stopped

networks:
  ssidl-network:
    external: true