#Uncomment the "servlet" and "context-path" lines below to make the fhir endpoint available at /example/path/fhir instead of the default value of /fhir
server:
  port: 8080
  tomcat:
    relaxed-query-chars: "|"
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health' # or e.g. 'info,health,prometheus,metrics' or '*' for all'
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
            - readinessState
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  main:
    allow-circular-references: true
  flyway:
    enabled: false
    baselineOnMigrate: true
    fail-on-missing-locations: false
  security:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
  datasource:
    url: jdbc:h2:mem:test_mem
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    max-active: 15
    #persistance-store:
    #    url: jdbc:postgresql://localhost:5432/ssidl_prototype
    #    username: ssidl
    #    password: 
    #    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false

      #Hibernate dialect is automatically detected except Postgres and H2.
      #If using H2, then supply the value of ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      #If using postgres, then supply the value of ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
  #      hibernate.hbm2ddl.auto: update
  #      hibernate.jdbc.batch_size: 20
  #      hibernate.cache.use_query_cache: false
  #      hibernate.cache.use_second_level_cache: false
  #      hibernate.cache.use_structured_entries: false
  #      hibernate.cache.use_minimal_puts: false

  ###    These settings will enable fulltext search with lucene or elastic
      hibernate.search.enabled: false
hapi:
  fhir:
    ### enable to set the Server URL
    serverAddress: http://localhost/fhir
    ### This is the FHIR version. Choose between, DSTU2, DSTU3, R4 or R5
    fhirVersion: R5
    ### This enables the swagger-ui at /fhir/swagger-ui/index.html as well as the /fhir/api-docs (see https://hapifhir.io/hapi-fhir/docs/server_plain/openapi.html)
    openApiEnabled: true
    ### Domyślna metoda serializacji zasobów
    defaultEncoding: JSON
    ### Domyślne formatowanie treści zasobów
    defaultPrettyPrint: true
    ### Konfiguracja obsługi atrybutów ETag odpowiedzi HTTP
    eTagSupportEnabled: true
    ### konfiguracja dozwolonych operacji usuwania zasobów
    deleteEnabled: true
    ### Konfiguracja obsługi generowania warstwy prezentacyjnej zasobów
    narrativeEnabled: false
    ### Konfiguracja obsługi pakietów NPM§
    packages:
      ### Konfiguracja adresów UR repozytoriów pakietów NPM
      primaryRegistryUrl: http://ssidl-nginx/registry/
      secondaryRegistryUrl: https://packages.fhir.org
      ### Konfiguracja pakietów NPM, które będą instalowane w trakcie uruchamiania serwera
      uploadEnabled: true
      uploadList:
        plbase:
          name: hl7.fhir.pl.base.r5
          version: 0.1.0
          type: IMPLEMENTATION_GUIDE
        ssidl:
          name: hl7.fhir.pl.ssidl
          version: 0.1.0
          type: IMPLEMENTATION_GUIDE
    ### Włączenie obsługi CORS
    cors:
      allowCredentials: true
      # These are allowed_origin patterns, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-
      allowedOrigin:
        - '*'
    ### Konfiguracja mechanizmów walidacji zasobów
    validation:
      requestsEnabled: true
      responsesEnabled: false
    ### Konfiguracja stronicowania odpowiedzi zwracanej przez serwer
    defaultPageSize: 20
    maxPageSize: 30    
    ### Konfiguracja osługi duzych zbiorów danych
    bulkExportEnabled: true
    bulkImportEnabled: true
    ### Konfiguracja czasu w minutach, przez jaki serwer będzie przechowywał wyniki wyszukiwania w pamięci podręcznej
    retainCachedSearchesMins: 60
    #### Konfiguracja czasu w milisekundach, przez jaki serwer będzie ponownie wykorzystywał wyniki wyszukiwania z pamięci podręcznej
    reuseCachedSearchResultsMillis: 60000
    ### Konfiguracja dopuszczalnych typów zasobów typu Bundle
    allowedBundleTypes: 
      - COLLECTION
      - DOCUMENT
      - MESSAGE
      - TRANSACTION
      - TRANSACTIONRESPONSE
      - BATCH
      - BATCHRESPONSE
      - HISTORY
      - SEARCHSET
    ### Konfiguracja lokalnych adresów bazowych
    localBaseUrls:
      - http://localhost/baseR5
    ### Konfiguracja adresów bazowych, które będą używane do rozwiązywania odwołań do zasobów  
    logicalUrls:
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*
      - http://snomed.info/*
      - https://snomed.info/*
      - http://unitsofmeasure.org/*
      - https://unitsofmeasure.org/*
      - http://loinc.org/*
      - https://loinc.org/*
    ### Konfiguracja obługiwanych natywnych typów zasobów HAPI FHIR
    supportedResourceTypes:
      - CapabilityStatement
      - ImplementationGuide
      - StructureDefinition
      - OperationDefinition
      - SearchParameter
      - ValueSet
      - CodeSystem
      - ConceptMap
      - NamingSystem
    ### Konfiguracja zdalnych zewnętrznych usług terminologicznych
    remoteTerminologyService:
      all:
        system: '*'
        url: 'https://tx.fhir.org/r4/'
